/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "projeto.h"

bool_t
xdr_pair (XDR *xdrs, pair *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->l))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->f))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operand (XDR *xdrs, operand *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->v, sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
