/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "projeto.h"
#include <math.h>


void
prog_100(char *host)
{
	CLIENT *clnt;
	pair  *result_1;
	operand  get_major_minor_100_arg;
	float * v = malloc(sizeof(float) * 10);

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
 
    for (int i = 0; i < 10; i++) {
        v[i] = (i - 5) * (i - 5);
    }

    for (int i = 0; i < 10; i++) {
        v[i] = sqrt(v[i]);
    }

	get_major_minor_100_arg.n = 10;
	get_major_minor_100_arg.v = v;

	result_1 = get_major_minor_100(&get_major_minor_100_arg, clnt);
	if (result_1 == (pair *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Minor: %f\n", result_1->f);
	printf("Major: %f\n", result_1->l);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	prog_100 (host);
exit (0);
}
