/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "projeto.h"
#include <math.h>
#include <pthread.h>


void
prog_100(int n, char ** hosts)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	pair result_1;
	operand * get_major_minor_100_arg = malloc(sizeof(operand));

	float *v = malloc(10 * sizeof(float));
 
    for (int i = 0; i < 10; i++) {
        v[i] = (i - 5) * (i - 5);
    }

    for (int i = 0; i < 10; i++) {
        v[i] = sqrt(v[i]);
    }

	// print v
	for (int i = 0; i < 10; i++) {
		printf("%f\n", v[i]);
	}

	get_major_minor_100_arg->n = 10;
	get_major_minor_100_arg->v = v;

#ifndef	DEBUG
	clnt = clnt_create (hosts[0], PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (hosts[0]);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = get_major_minor_100(get_major_minor_100_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

	// print results
	printf("%f\n", result_1.f);
	printf("%f\n", result_1.l);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	if (argc < 2) {
		printf ("usage: %s server_host1 server_host2 ... server_hostN\n", argv[0]);
		exit (1);
	}
	char **hosts;

	hosts = (char **) malloc(sizeof(char *) * (argc-1));
	for (int i = 1; i < argc; i++) {
		hosts[i-1] = argv[i];
	}

	prog_100 (argc-1, hosts);
exit (0);
}
