/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROJETO_H_RPCGEN
#define _PROJETO_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct pair {
	float l;
	float f;
};
typedef struct pair pair;

struct operand {
	int n;
	float *v;
};
typedef struct operand operand;

#define PROG 66666666
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define GET_MAJOR_MINOR 1
extern  enum clnt_stat get_major_minor_100(operand *, pair *, CLIENT *);
extern  bool_t get_major_minor_100_svc(operand *, pair *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_MAJOR_MINOR 1
extern  enum clnt_stat get_major_minor_100();
extern  bool_t get_major_minor_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_pair (XDR *, pair*);
extern  bool_t xdr_operand (XDR *, operand*);

#else /* K&R C */
extern bool_t xdr_pair ();
extern bool_t xdr_operand ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROJETO_H_RPCGEN */
