/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "projeto.h"

pair get_minor_and_major(int n, float * v) {
    int i;
    float min, max;
    min = max = v[0];
    for (i = 1; i < n; i++) {
        if (v[i] < min) {
            min = v[i];
        }
        if (v[i] > max) {
            max = v[i];
        }
    }

    pair p;
    p.f = min;
    p.l = max;

    return p;
}

pair *
get_major_minor_100_svc(operand *argp, struct svc_req *rqstp)
{
	static pair  result;

	printf("%d\n", argp->n);

	for (int i = 0; i < argp->n; i++) {
		printf("v[%d]: %f \n", i, argp->v[i]);
	}

	result = get_minor_and_major(argp->n, argp->v);

	return &result;
}
