/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "projeto.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

pair *
get_major_minor_100(operand *argp, CLIENT *clnt)
{
	static pair clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_MAJOR_MINOR,
		(xdrproc_t) xdr_operand, (caddr_t) argp,
		(xdrproc_t) xdr_pair, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
